# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x02pb\"<\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\r\x12\x1a\n\x06sensor\x18\x03 \x01(\x0b\x32\n.pb.Sensor\"@\n\x06Sensor\x12\x13\n\x0btemperature\x18\x01 \x01(\r\x12\x10\n\x08humidity\x18\x02 \x01(\r\x12\x0f\n\x07voltage\x18\x03 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=18
  _globals['_DATA']._serialized_end=78
  _globals['_SENSOR']._serialized_start=80
  _globals['_SENSOR']._serialized_end=144
# @@protoc_insertion_point(module_scope)
